# Generated by Django 4.1.2 on 2024-01-30 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0002_alter_typedocument_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typedocument',
            name='description',
            field=models.CharField(error_messages={'blank': 'La descripción es requerida', 'null': 'La descripción es requerida'}, max_length=255),
        ),
    ]
