# Generated by Django 4.1.2 on 2024-01-30 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0003_alter_typedocument_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typedocument',
            name='description',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
