# Generated by Django 4.1.2 on 2024-01-31 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_users_encryptedpassword'),
        ('misc', '0004_alter_typedocument_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeDocumentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.users')),
            ],
            options={
                'verbose_name': 'type_document_log',
                'verbose_name_plural': 'type_documents_log',
                'db_table': 'type_documents_log',
            },
        ),
    ]
