# Generated by Django 4.1.2 on 2024-02-01 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0005_typedocumentlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typedocumentlog',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
