# Generated by Django 4.1.2 on 2024-02-01 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0006_alter_typedocumentlog_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='typedocumentlog',
            name='updatedFields',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
