# Generated by Django 4.1.2 on 2024-02-01 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0007_typedocumentlog_updatedfields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='typedocumentlog',
            old_name='updatedFields',
            new_name='newValues',
        ),
        migrations.AddField(
            model_name='typedocumentlog',
            name='previousValues',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
