# Generated by Django 4.1.2 on 2024-02-01 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0009_remove_typedocumentlog_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='typedocumentlog',
            name='typeDocument',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='misc.typedocument'),
            preserve_default=False,
        ),
    ]
