# Generated by Django 4.1.2 on 2024-02-06 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_remove_permissionlog_description_and_more'),
        ('misc', '0010_typedocumentlog_typedocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='typedocument',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='authentication.users'),
            preserve_default=False,
        ),
    ]
