# Generated by Django 4.1.2 on 2024-02-06 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0011_typedocument_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typedocument',
            name='user',
        ),
    ]
