# Generated by Django 4.1.2 on 2024-02-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0012_remove_typedocument_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='typedocument',
            name='abbreviation',
            field=models.CharField(default=None, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
