# Generated by Django 4.1.2 on 2024-03-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0015_subcategory_subcategorylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='code',
            field=models.CharField(default=None, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
