# Generated by Django 4.1.2 on 2024-03-05 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0017_subcategory_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategorylog',
            old_name='sub_category',
            new_name='subCategory',
        ),
    ]
