# Generated by Django 4.1.2 on 2024-03-08 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0023_menu_url'),
        ('misc', '0019_alter_category_code_alter_category_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holyday',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('state', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at_unix', models.BigIntegerField(editable=False)),
                ('updated_at_unix', models.BigIntegerField(editable=False, null=True)),
                ('year', models.CharField(error_messages={'unique': 'Ya existe una categoría con este código'}, max_length=10, unique=True)),
                ('month', models.CharField(error_messages={'unique': 'Ya existe una categoría con este código'}, max_length=10, unique=True)),
                ('day', models.CharField(error_messages={'unique': 'Ya existe una categoría con este código'}, max_length=10, unique=True)),
                ('description', models.CharField(error_messages={'unique': 'Ya existe una categoría con este nombre'}, max_length=255, unique=True)),
                ('user_created_at', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_at', to='authentication.users')),
                ('user_updated_at', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_at', to='authentication.users')),
            ],
            options={
                'verbose_name': 'holyday',
                'verbose_name_plural': 'holydays',
                'db_table': 'holydays',
            },
        ),
        migrations.CreateModel(
            name='HolydayLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=255)),
                ('previousValues', models.JSONField(blank=True, null=True)),
                ('newValues', models.JSONField(blank=True, null=True)),
                ('holyday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc.holyday')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.users')),
            ],
            options={
                'verbose_name': 'holyday_log',
                'verbose_name_plural': 'holydays_log',
                'db_table': 'holydays_log',
            },
        ),
    ]
