# Generated by Django 4.1.2 on 2024-03-08 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0020_holyday_holydaylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holyday',
            name='day',
            field=models.CharField(error_messages={'unique': 'Ya existe una categoría con este código'}, max_length=10),
        ),
        migrations.AlterField(
            model_name='holyday',
            name='description',
            field=models.CharField(error_messages={'unique': 'Ya existe una categoría con este nombre'}, max_length=255),
        ),
        migrations.AlterField(
            model_name='holyday',
            name='month',
            field=models.CharField(error_messages={'unique': 'Ya existe una categoría con este código'}, max_length=10),
        ),
        migrations.AlterField(
            model_name='holyday',
            name='year',
            field=models.CharField(error_messages={'unique': 'Ya existe una categoría con este código'}, max_length=10),
        ),
    ]
