# Generated by Django 4.1.2 on 2024-01-30 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_At', models.DateTimeField(auto_now_add=True)),
                ('model', models.CharField(max_length=255)),
                ('action', models.CharField(max_length=255)),
                ('user', models.CharField(max_length=255)),
                ('data', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
