# Generated by Django 4.1.2 on 2024-01-30 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_activitylog_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'verbose_name': 'activity_log', 'verbose_name_plural': 'activity_log'},
        ),
        migrations.RenameField(
            model_name='activitylog',
            old_name='created_At',
            new_name='created_at',
        ),
        migrations.AlterModelTable(
            name='activitylog',
            table='activity_logs',
        ),
    ]
