# Generated by Django 4.1.2 on 2024-01-31 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_activitylog_changes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActivityLog',
        ),
    ]
