# Generated by Django 4.1.2 on 2024-02-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0005_delete_activitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True, null=True)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'request_log',
                'verbose_name_plural': 'request_logs',
                'db_table': 'request_logs',
            },
        ),
    ]
