# Generated by Django 4.1.2 on 2024-02-06 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_users_custom_permissions_alter_role_permissions'),
        ('base', '0006_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.users'),
        ),
    ]
