# Generated by Django 4.1.2 on 2024-01-30 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_users_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='encryptedPassword',
        ),
    ]
