# Generated by Django 4.1.2 on 2024-02-05 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_role_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='roles_permission', to='authentication.permission'),
        ),
    ]
