# Generated by Django 4.1.2 on 2024-02-05 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_role_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='custom_permissions',
            field=models.ManyToManyField(blank=True, related_name='users_custom_permission', to='authentication.permission'),
        ),
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='roles_clearpermission', to='authentication.permission'),
        ),
    ]
