# Generated by Django 4.1.2 on 2024-02-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_users_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='username'),
        ),
    ]
