# Generated by Django 4.1.2 on 2024-02-06 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_users_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone_number',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UsersLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=255)),
                ('previousValues', models.JSONField(blank=True, null=True)),
                ('newValues', models.JSONField(blank=True, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='last name')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='username')),
                ('password', models.CharField(blank=True, max_length=255, null=True, verbose_name='password')),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('custom_permissions', models.ManyToManyField(blank=True, related_name='users_custom_permission_log', to='authentication.permission')),
                ('roles', models.ManyToManyField(blank=True, related_name='users_role_log', to='authentication.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.users')),
            ],
            options={
                'verbose_name': 'user_log',
                'verbose_name_plural': 'users_logs',
                'db_table': 'users_logs',
            },
        ),
        migrations.CreateModel(
            name='RoleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=255)),
                ('previousValues', models.JSONField(blank=True, null=True)),
                ('newValues', models.JSONField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles_clearpermission_log', to='authentication.permission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.users')),
            ],
            options={
                'verbose_name': 'role_log',
                'verbose_name_plural': 'roles_logs',
                'db_table': 'roles_logs',
            },
        ),
        migrations.CreateModel(
            name='PermissionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=255)),
                ('previousValues', models.JSONField(blank=True, null=True)),
                ('newValues', models.JSONField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.users')),
            ],
            options={
                'verbose_name': 'permission_log',
                'verbose_name_plural': 'permissions_logs',
                'db_table': 'permissions_logs',
            },
        ),
    ]
