# Generated by Django 4.1.2 on 2024-02-06 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_users_password_alter_users_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permissionlog',
            name='description',
        ),
        migrations.RemoveField(
            model_name='rolelog',
            name='description',
        ),
        migrations.RemoveField(
            model_name='rolelog',
            name='permissions',
        ),
        migrations.RemoveField(
            model_name='userslog',
            name='code',
        ),
        migrations.RemoveField(
            model_name='userslog',
            name='custom_permissions',
        ),
        migrations.RemoveField(
            model_name='userslog',
            name='description',
        ),
        migrations.RemoveField(
            model_name='userslog',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userslog',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userslog',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='userslog',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='userslog',
            name='password',
        ),
        migrations.RemoveField(
            model_name='userslog',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='userslog',
            name='roles',
        ),
        migrations.RemoveField(
            model_name='userslog',
            name='username',
        ),
        migrations.AddField(
            model_name='permissionlog',
            name='permission',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='permission_log_permission', to='authentication.permission'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rolelog',
            name='role',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='role_log_role', to='authentication.role'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userslog',
            name='users',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='users_log_user', to='authentication.users'),
            preserve_default=False,
        ),
    ]
