# Generated by Django 4.2.2 on 2024-02-08 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_alter_role_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='code',
        ),
        migrations.RemoveField(
            model_name='users',
            name='phone_number',
        ),
    ]
