# Generated by Django 4.2.2 on 2024-02-08 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='expiration',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
