# Generated by Django 4.1.2 on 2024-02-21 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0012_remove_typedocument_user'),
        ('authentication', '0017_token_expiration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('state', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at_unix', models.BigIntegerField(editable=False)),
                ('updated_at_unix', models.BigIntegerField(editable=False, null=True)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'menu',
                'verbose_name_plural': 'menus',
                'db_table': 'menus',
            },
        ),
        migrations.RemoveField(
            model_name='users',
            name='description',
        ),
        migrations.AddField(
            model_name='users',
            name='document_number',
            field=models.CharField(default=None, max_length=255, verbose_name='document_number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='is_ldap_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='phone_number'),
        ),
        migrations.AddField(
            model_name='users',
            name='type_document',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='users_type_document', to='misc.typedocument'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='MenuLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=255)),
                ('previousValues', models.JSONField(blank=True, null=True)),
                ('newValues', models.JSONField(blank=True, null=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_log_menu', to='authentication.menu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.users')),
            ],
            options={
                'verbose_name': 'menu_log',
                'verbose_name_plural': 'menus_logs',
                'db_table': 'menus_logs',
            },
        ),
        migrations.AddField(
            model_name='menu',
            name='user_created_at',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_at', to='authentication.users'),
        ),
        migrations.AddField(
            model_name='menu',
            name='user_updated_at',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_at', to='authentication.users'),
        ),
    ]
