# Generated by Django 4.1.2 on 2024-02-21 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_menu_remove_users_description_users_document_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='first_name',
            field=models.CharField(default=None, max_length=255, verbose_name='first name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='last_name',
            field=models.CharField(default=None, max_length=255, verbose_name='last name'),
            preserve_default=False,
        ),
    ]
