# Generated by Django 4.1.2 on 2024-02-21 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_users_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='icon',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
