# Generated by Django 4.1.2 on 2024-02-21 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0021_menu_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='menus',
            field=models.ManyToManyField(blank=True, related_name='roles_menu', to='authentication.menu'),
        ),
    ]
