# Generated by Django 4.1.2 on 2024-02-21 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0022_role_menus'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='url',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
