# Generated by Django 4.1.2 on 2024-03-06 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0023_menu_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrganization',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('state', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at_unix', models.BigIntegerField(editable=False)),
                ('updated_at_unix', models.BigIntegerField(editable=False, null=True)),
                ('code', models.CharField(blank=True, error_messages={'unique': 'Ya existe una organizacion de compra con este código'}, max_length=10, null=True, unique=True)),
                ('description', models.CharField(error_messages={'unique': 'Ya existe una organizacion de compra con este nombre'}, max_length=255, unique=True)),
                ('user_created_at', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_at', to='authentication.users')),
                ('user_updated_at', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_at', to='authentication.users')),
            ],
            options={
                'verbose_name': 'purchase_organization',
                'verbose_name_plural': 'purchase_organizations',
                'db_table': 'purchase_organizations',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrganizationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=255)),
                ('previousValues', models.JSONField(blank=True, null=True)),
                ('newValues', models.JSONField(blank=True, null=True)),
                ('purchaseOrganization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.purchaseorganization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.users')),
            ],
            options={
                'verbose_name': 'purchase_organization_log',
                'verbose_name_plural': 'purchase_organizations_log',
                'db_table': 'purchase_organizations_log',
            },
        ),
    ]
