# Generated by Django 4.1.2 on 2024-03-06 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0023_menu_url'),
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogisticCenter',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('state', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at_unix', models.BigIntegerField(editable=False)),
                ('updated_at_unix', models.BigIntegerField(editable=False, null=True)),
                ('code', models.CharField(blank=True, error_messages={'unique': 'Ya existe un centro logístico con este código'}, max_length=10, null=True, unique=True)),
                ('description', models.CharField(error_messages={'unique': 'Ya existe un centro logístico con este nombre'}, max_length=255, unique=True)),
                ('user_created_at', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_at', to='authentication.users')),
                ('user_updated_at', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_at', to='authentication.users')),
            ],
            options={
                'verbose_name': 'logistic_center',
                'verbose_name_plural': 'logistic_centers',
                'db_table': 'logistic_centers',
            },
        ),
        migrations.CreateModel(
            name='LogisticCenterLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=255)),
                ('previousValues', models.JSONField(blank=True, null=True)),
                ('newValues', models.JSONField(blank=True, null=True)),
                ('logisticCenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.logisticcenter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.users')),
            ],
            options={
                'verbose_name': 'logistic_center_log',
                'verbose_name_plural': 'logistic_centers_log',
                'db_table': 'logistic_centers_log',
            },
        ),
    ]
