# Generated by Django 4.1.2 on 2024-03-06 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0023_menu_url'),
        ('request', '0004_costcenter_costcenterlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolcotType',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('state', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at_unix', models.BigIntegerField(editable=False)),
                ('updated_at_unix', models.BigIntegerField(editable=False, null=True)),
                ('description', models.CharField(error_messages={'unique': 'Ya existe un tipo de solcot con este nombre'}, max_length=255, unique=True)),
                ('days', models.IntegerField()),
                ('user_created_at', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_at', to='authentication.users')),
                ('user_updated_at', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_at', to='authentication.users')),
            ],
            options={
                'verbose_name': 'solcot_type',
                'verbose_name_plural': 'solcot_types',
                'db_table': 'solcot_types',
            },
        ),
        migrations.CreateModel(
            name='SolcotTypeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=255)),
                ('previousValues', models.JSONField(blank=True, null=True)),
                ('newValues', models.JSONField(blank=True, null=True)),
                ('solcotType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.solcottype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.users')),
            ],
            options={
                'verbose_name': 'solcot_type_log',
                'verbose_name_plural': 'solcot_types_log',
                'db_table': 'solcot_types_log',
            },
        ),
    ]
