# Generated by Django 4.1.2 on 2024-03-07 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0006_tax_taxlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solcottype',
            name='days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
