# Generated by Django 4.1.2 on 2024-03-07 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0019_alter_category_code_alter_category_description'),
        ('authentication', '0023_menu_url'),
        ('request', '0007_alter_solcottype_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupraSolcot',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('state', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at_unix', models.BigIntegerField(editable=False)),
                ('updated_at_unix', models.BigIntegerField(editable=False, null=True)),
                ('client_email', models.EmailField(max_length=255)),
                ('viewed_by_buyer', models.BooleanField(default=False)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('process_state', models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('ACEPTADO', 'ACEPTADO'), ('RECHAZADO', 'RECHAZADO'), ('RESTORE', 'RESTORE'), ('FINALIZADO', 'FINALIZADO'), ('VENCIDA', 'VENCIDA'), ('CERRADO', 'CERRADO'), ('REVISION', 'REVISION'), ('DEVUELTA', 'DEVUELTA')], default='PENDIENTE', max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc.category')),
                ('purchase_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.purchaseorganization')),
                ('shopping_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.shoppinggroup')),
                ('solcot_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.solcottype')),
                ('user_created_at', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_at', to='authentication.users')),
                ('user_updated_at', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_at', to='authentication.users')),
            ],
            options={
                'verbose_name': 'supra_solcot',
                'verbose_name_plural': 'supra_solcot',
                'db_table': 'supra_solcot',
            },
        ),
        migrations.CreateModel(
            name='SupraSolcotLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=255)),
                ('previousValues', models.JSONField(blank=True, null=True)),
                ('newValues', models.JSONField(blank=True, null=True)),
                ('supraSolcot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.suprasolcot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.users')),
            ],
            options={
                'verbose_name': 'supra_solcot_log',
                'verbose_name_plural': 'supra_solcot_log',
                'db_table': 'supra_solcot_log',
            },
        ),
    ]
