# Generated by Django 4.1.2 on 2024-03-07 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0019_alter_category_code_alter_category_description'),
        ('authentication', '0023_menu_url'),
        ('request', '0008_suprasolcot_suprasolcotlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solcot',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('state', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at_unix', models.BigIntegerField(editable=False)),
                ('updated_at_unix', models.BigIntegerField(editable=False, null=True)),
                ('consecutive', models.CharField(error_messages={'unique': 'Ya existe un solcot con este consecutivo'}, max_length=255, unique=True)),
                ('product', models.CharField(max_length=255)),
                ('quantity', models.FloatField()),
                ('measurementUnit', models.CharField(max_length=255)),
                ('budget', models.FloatField()),
                ('specification', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('limit_date', models.DateTimeField()),
                ('is_unique_provider', models.BooleanField(default=False)),
                ('is_visit_required', models.BooleanField(default=False)),
                ('contract_manager', models.CharField(max_length=255)),
                ('solpet_code', models.CharField(blank=True, max_length=255, null=True)),
                ('global_administration', models.FloatField(blank=True, null=True)),
                ('global_utility', models.FloatField(blank=True, null=True)),
                ('global_contingencies', models.FloatField(blank=True, null=True)),
                ('is_viewed_by_buyer', models.BooleanField(default=False)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('process_state', models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('ACEPTADO', 'ACEPTADO'), ('RECHAZADO', 'RECHAZADO'), ('RESTORE', 'RESTORE'), ('FINALIZADO', 'FINALIZADO'), ('VENCIDA', 'VENCIDA'), ('CERRADO', 'CERRADO'), ('REVISION', 'REVISION'), ('DEVUELTA', 'DEVUELTA')], default='PENDIENTE', max_length=255)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solcot_buyer', to='authentication.users')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc.category')),
                ('logistic_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.logisticcenter')),
                ('purchase_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.purchaseorganization')),
                ('shopping_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.shoppinggroup')),
                ('solcot_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.solcottype')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc.subcategory')),
            ],
            options={
                'verbose_name': 'solcot',
                'verbose_name_plural': 'solcot',
                'db_table': 'solcot',
            },
        ),
        migrations.AddField(
            model_name='suprasolcot',
            name='logistic_center',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='request.logisticcenter'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SolcotLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=255)),
                ('previousValues', models.JSONField(blank=True, null=True)),
                ('newValues', models.JSONField(blank=True, null=True)),
                ('solcot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.solcot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.users')),
            ],
            options={
                'verbose_name': 'solcot_log',
                'verbose_name_plural': 'solcot_log',
                'db_table': 'solcot_log',
            },
        ),
        migrations.AddField(
            model_name='solcot',
            name='supra_solcot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.suprasolcot'),
        ),
        migrations.AddField(
            model_name='solcot',
            name='user_created_at',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_at', to='authentication.users'),
        ),
        migrations.AddField(
            model_name='solcot',
            name='user_updated_at',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_at', to='authentication.users'),
        ),
    ]
