# Generated by Django 4.1.2 on 2024-03-07 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0023_menu_url'),
        ('request', '0009_solcot_suprasolcot_logistic_center_solcotlog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('state', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at_unix', models.BigIntegerField(editable=False)),
                ('updated_at_unix', models.BigIntegerField(editable=False, null=True)),
                ('description', models.TextField()),
                ('solcot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.solcot')),
                ('supra_solcot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.suprasolcot')),
                ('user_created_at', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_at', to='authentication.users')),
                ('user_updated_at', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_at', to='authentication.users')),
            ],
            options={
                'verbose_name': 'observation',
                'verbose_name_plural': 'observations',
                'db_table': 'observations',
            },
        ),
        migrations.CreateModel(
            name='ObservationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=255)),
                ('previousValues', models.JSONField(blank=True, null=True)),
                ('newValues', models.JSONField(blank=True, null=True)),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.observation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.users')),
            ],
            options={
                'verbose_name': 'observation_log',
                'verbose_name_plural': 'observations_log',
                'db_table': 'observations_log',
            },
        ),
    ]
