# Generated by Django 4.1.2 on 2024-03-07 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0023_menu_url'),
        ('request', '0010_observation_observationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='suprasolcot',
            name='client',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='supra_solcot_client', to='authentication.users'),
            preserve_default=False,
        ),
    ]
