# Generated by Django 4.1.2 on 2024-03-07 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0011_suprasolcot_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solcot',
            name='limit_date',
            field=models.DateField(),
        ),
    ]
