# Generated by Django 4.1.2 on 2024-03-11 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0013_alter_solcot_limit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solcot',
            name='limit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
