# Generated by Django 4.1.2 on 2024-03-18 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0015_remove_solcot_sub_category_solcot_sub_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solcot',
            name='limit_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
